name: CoinWizards CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install react-bootstrap bootstrap
      - run: npm install – -save react-router-dom
      - run: npm install react-bootstrap bootstrap
      - run: npm init @eslint/config
      - run: npx eslint .
